title: Walker Lab
email: jfw52@cam.ac.uk
twitter_username: evojfwalker
github_username: jfwalker

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - introduction.md
  - teaching.md
  - outreach.md
  - publication.md

